name: .NET Framework CI

on: [push, pull_request]

permissions:
  contents: write
  packages: write

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/changelog

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Restore dependencies
        run: |
          msbuild /t:restore
          nuget restore

      - name: Build
        run: msbuild /p:Configuration=Release /p:Platform="Any CPU"

      - name: Publish
        run: msbuild /t:Publish /p:Configuration=Release /p:Platform="Any CPU"

      - name: Archive JudgeSystem DLL
        uses: actions/upload-artifact@v4
        with:
          name: JudgeSystem
          path: |
            bin/Release/JudgeSystem.dll
            bin/Release/JudgeSystem.pdb
      
      - name: Archive JudgeSystem 2024uc
        uses: actions/upload-artifact@v4
        with:
          name: JudgeSystem 2024uc
          path: |
            2024uc/bin/Release/JudgeSystem.2024uc.dll
            2024uc/bin/Release/JudgeSystem.2024uc.pdb
            
      - name: Archive JudgeSystem 2024ul
        uses: actions/upload-artifact@v4
        with:
          name: JudgeSystem 2024ul
          path: |
            2024ul/bin/Release/JudgeSystem.2024ul.dll
            2024ul/bin/Release/JudgeSystem.2024ul.pdb

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}